# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200, verbose_name=b'tema')),
                ('descricao', models.TextField(verbose_name=b'descri\xc3\xa7\xc3\xa3o')),
                ('abertura_atividade', models.DateTimeField(verbose_name=b'abertura')),
                ('encerramento_atividade', models.DateTimeField(verbose_name=b'encerramento')),
                ('local', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'local de realiza\xc3\xa7\xc3\xa3o')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name=b'nome')),
                ('local', models.CharField(max_length=200, verbose_name=b'local')),
                ('abertura_evento', models.DateField(verbose_name=b'abertura do evento')),
                ('encerramento_evento', models.DateField(verbose_name=b'encerramento do evento')),
                ('abertura_inscricoes', models.DateField(verbose_name=b'abertura das inscri\xc3\xa7\xc3\xb5es')),
                ('encerramento_inscricoes', models.DateField(verbose_name=b'encerramento das inscri\xc3\xa7\xc3\xb5es')),
                ('limite_inscricoes', models.IntegerField(verbose_name=b'limite de inscri\xc3\xa7\xc3\xb5es')),
                ('apresentacao', models.TextField(blank=True, null=True, verbose_name=b'apresenta\xc3\xa7\xc3\xa3o')),
                ('publico_alvo', models.TextField(blank=True, null=True, verbose_name=b'p\xc3\xbablico alvo')),
                ('programacao', models.TextField(blank=True, null=True, verbose_name=b'programa\xc3\xa7\xc3\xa3o')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'data de cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, unique=True, verbose_name=b'descri\xc3\xa7\xc3\xa3o')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'data de cadastro')),
            ],
            options={
                'verbose_name': 'tipo de atividade',
                'verbose_name_plural': 'tipos de atividades',
            },
        ),
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.TipoAtividade'),
        ),
    ]
